### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by OhArentYouCutenot** [martenson/disposable-email-domains#152]
DEA is primarily employed by **Privacy Enthusiasts*  of all political flavors as cretinous behavior from a variety of offered-as-no-cost-by-the-irrational services **abuse the email of users**.

So you blacklist a subset of DEA domains? wow.  What stops the Privacy Minded Folk from creating a free webmail account, or their own domain atop free email service -- _NEVER_ looking at a given inbox after account creation?

Yes, blacklisting DEA is about as effective as making murder illegalER. [sic]   The spammers you fear have worse morals than those who employ DEA blocking.  Punishing licit users only inspires greater ANTISPAM creativity... continuing to thwart your abuse of the naive or weak.

**Comment by C0nw0nk** [comment]
Why are you complaining if people want to block your domains they will block your domains you are not going to change their minds, Everyone has their own solutions and tactics to tackle problems and would use the lists provided for a vast variety of other reasons than those you single mindedly think of for yourself.

You should understand open MX records are a security issue that can result in hijacked accounts. Example :
User registers with a disposable email
Someone can use that disposable email to hijack that users registered account on a site using the forgotten password or account forms.

Disposable emails are their own worst enemy due to the unsecured nature of them since anybody can access and view those emails since they are public.

You should take your salty bitterness and keep it to yourself, Go complain about adblock blacklists as another example.

**Comment by martenson** [comment]
@C0nw0nk Thank you for your tactful response.

@OhArentYouCutenot I am happy this simple domain list was the reason you created a GitHub account. Good luck with your future open source work.
